sudo: required
dist: trusty
addons:
  apt:
    packages:
    - bochs-term
    - qemu
    - python3
    - python3-pip
    - expect-dev
language: bash

script:
  - sudo pip3 install asciinema
  - chmod +x ./script
  - sudo /bin/bash -c ./script
